#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

#
# nethserver-samba-audit-update event
#

my $event = "nethserver-samba-audit-update";

event_actions($event, qw(
      initialize-default-databases 00
      nethserver-samba-audit-conf 02
));

event_templates($event, qw(
      /etc/httpd/conf.d/smbaudit.conf
      /etc/samba/smb.conf
));

event_services($event, qw(
      httpd reload
      rsyslog restart
      smb reload
));


#
# nethserver-samba-audit-save event
#

$event = "nethserver-samba-audit-save";

event_templates($event, qw(
      /etc/samba/smb.conf
));

event_services($event, qw(
      smb reload
));

