#!/usr/bin/perl -w

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks qw(:all);

#
# nethserver-samba-audit-update event
#

my $event = "nethserver-samba-audit-update";

event_actions($event, qw(
      initialize-default-databases 00
      nethserver-samba-audit-conf 02
));

event_templates($event, qw(
      /etc/httpd/conf.d/smbaudit.conf
      /etc/httpd/admin-conf.d/smbaudit.conf
      /etc/samba/smb.conf
      /usr/share/smbaudit/config/config.php
));

event_services($event, qw(
      httpd reload
      httpd-admin reload
      rsyslog restart
      smb reload
));


#
# nethserver-samba-audit-save event
#

$event = "nethserver-samba-audit-save";

event_templates($event, qw(
      /etc/samba/smb.conf
));

event_services($event, qw(
      smb reload
));

#
# migration-import event
#

$event = "migration-import";
event_actions($event, 'nethserver-samba-audit-migrate' => 50);

